
combinations:
  #index: dinde
  index: &combinations_index |
    A combination is a set composed of a DHCP fingerprint, DHCPv6 fingerprint DHCP vendor, DHCP enterprise, User Agent and a MAC vendor.
    These combinations have an associated device (usually representing the OS) and OS version.
    The combinations have an associated score reprensenting the chances that the device found is correct.
    A score below 50 usually means that it was computed using insecure informations like the user agent.
    A score above 50 means that the chances are good the device was correctly detected
    You can submit an unknown combination using the 'Submit Combination' button.

    <strong>Search:</strong>
    By default, the search uses a like to match the entries. This means that it searches for partial matching.
    To have your query match the beginning add ^ at the beginning of your query.
    To have your query match the end add $ at the end of your query.

  unrated_before: |
    The unrated combinations that you see here have been submitted by the community but haven't been approved yet.
  unrated: *combinations_index

  unknown_before: | 
    The unknown combinations that you see here haven't been sorted yet 
  unknown: *combinations_index
    
  new: |
    Here you can submit a combination that you have.
    If you can't find your device in the list, feel free to add it by clicking the 'Not listed ?' link
    Enter the information that you have for the device. If some information is missing, simply leave it empty.

devices:
  index: |
    These are all the devices that are known to Fingerbank.
    Click on the eye next to a device to have more information about it.
    If a device has children you can show those clicking the button at the left of the device to expand the tree.
  show: |
    <strong>Fields explanation</strong>
    Full path : Is the concatenation of all the names of the device parents and the device name
    Attributes : This will show you if the device is a mobile and/or a tablet
    These attributes may not be accurate if Fingerbank has not a combination matching that device.
    N.B. : A tablet device is considered mobile

    The discoverers that find combinations belonging to that device are listed below.

discoverers:
  index: |
    The discoverers listed here are the core of Fingerbank.
    These will parse the data that is sent to Fingerbank in order to categorize the combination of DHCP fingerprint, DHCP vendor, DHCPv6 fingerprint, DHCPv6 enterprise, User Agent and MAC vendor.
  show: |
    On this page you can see the attributes that define the discoverer.
    The priority is the amount that will be added to a device score if one of the device rules matches the combination.
    The version is either an SQL extractor for the version or simply the version of the device when matching any version rule.
    The device is the associated device to that discoverer. When matching it, it means the combination belongs to this device.
    The devices rules are what matches the combination attributes and if they match then this discoverer is valid for that combination.
    The version rules are what attributes a combination should match in order to be attributed the specified version in the discoverer.

    <strong>Rules :</strong>
    The rules use the SQL syntax and are injected into a query to perform the match.
    The tables available for the match are : dhcp_fingerprints, dhcp_vendors, dhcp6_fingerprints, dhcp6_enterprises, user_agents, mac_vendors
    For more information on the fields, refer to the SQL schema.
    The value is the raw stored query that may contain additionnal variables that are conditions.
